name: mini-run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  mini:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy==2.1.3 scipy==1.16.2 matplotlib==3.10.7
      - name: Validate publish summary
        run: |
          python - <<'PY'
          import os, json, sys
          p = 'env/wcct_umatrix_outputs/publish/summary.json'
          if not os.path.isfile(p):
            print(f"ERROR: missing {p}")
            sys.exit(1)
          with open(p) as f:
            j = json.load(f)
          required = ['spearman_full','mi_full','jaccard_q85','enrichment_q85']
          missing = [k for k in required if k not in j]
          if missing:
            print("ERROR: missing keys:", missing)
            sys.exit(1)
          print("mini-run OK:", {k: j[k] for k in required})
          PY
