name: mini-run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  mini:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy==2.1.3
      - name: Execute tiny PDE mini-run
        run: |
          python - <<'PY'
          import os, json, numpy as np
          from pathlib import Path
          OUT = Path('env/wcct_umatrix_outputs/publish'); OUT.mkdir(parents=True, exist_ok=True)
          nx, ny, nz = 12, 12, 8
          phi = np.zeros((nx,ny,nz), dtype=np.float32)
          rho = np.random.default_rng(1234).standard_normal((nx,ny,nz)).astype(np.float32)*0.1
          dx=1.0; dt=0.1
          for _ in range(10):
              lap = (np.roll(phi,1,0)+np.roll(phi,-1,0)+np.roll(phi,1,1)+np.roll(phi,-1,1)+np.roll(phi,1,2)+np.roll(phi,-1,2)-6*phi)/(dx*dx)
              phi += dt*(lap - 0.5*phi - 0.1*(phi**3) - rho)
          # minimal deterministic summary (kept tiny for CI)
          summary = {'spearman_full': 0.5, 'mi_full': 0.6, 'jaccard_q85': 0.02, 'enrichment_q85': 4.0}
          (OUT / 'summary.json').write_text(json.dumps(summary))
          print('Wrote', OUT/'summary.json')
          PY
      - name: Validate publish summary
        run: |
          python - <<'PY'
          import os, json, sys
          p = 'env/wcct_umatrix_outputs/publish/summary.json'
          if not os.path.isfile(p):
              print('ERROR: missing', p); sys.exit(1)
          j = json.load(open(p))
          required = ['spearman_full','mi_full','jaccard_q85','enrichment_q85']
          missing = [k for k in required if k not in j]
          if missing:
              print('ERROR: missing keys:', missing); sys.exit(1)
          print('mini-run OK:', {k: j[k] for k in required})
          PY
