name: smoke
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Verify repo layout
        run: |
          test -f env/U_matrix_WCCT.ipynb
          test -d env/wcct_umatrix_outputs/publish
          ls -1 env/wcct_umatrix_outputs/publish | head -n 20
